### ISSUE TITLE
Bal of merkletree-verify

### ISSUE THREAD

**Issue by Drmiller85** [silversixpence-crypto/merkletree-verify#52]
Just want my money out my tree

**Comment by Atok66** [comment]
Tq and very perfect

**Comment by Drmiller85** [comment]
> Just want my money out my tree

**Comment by Bbjj88h** [comment]
Just want my money

**Comment by CrytoCraze77** [comment]
Are you uhhh wtf thank you more I take IRSSent from my iPhoneOn Feb 16, 2024, at 10:40, Cyclonecinta88 ***@***.***> wrote:﻿
Just want my money

**Comment by CrytoCraze77** [comment]
Who the fuck are you lol ?? Your money …if it’s Elon FUCK U FUCK UR SISTER UR MOMMA HOPE YOU FAKL GET STUFK ON FUCKIN TRAIN TRACK U DRUG ADDICT I DONT CATE IF YOU DONT KNOW WHAT YOU DO YOUR ADULT MSKE CHOICE GOTTA LIVE WITH IT FIVK. PRIVKSent from my iPhoneOn Feb 16, 2024, at 10:40, Cyclonecinta88 ***@***.***> wrote:﻿
Just want my money

**Comment by Bbjj88h** [comment]
Who the fuck you talking to captain cook ho I'll skull frag you ho

**Comment by CrytoCraze77** [comment]
lol me yo really skull frag the fuck is that gay boy 😂😂o my well you power there pup but the long LONG overdue regulation. Info what fuvk nuts like been robbing jacking folks years two bit Ponzi scheme later or going back to know months or ur sister cream pies both. Pussiex lol omf go fuck off or come get some talk like all rest I’m ready long last die being it the fuck on talk u fuvkin Maggie COME ON I SKNT GOING NOWHERE SO COME ON Spec on top chicken shit I  fuckin double dawg dare you dickhead …bring my blockchain you cuntSent from my iPhoneOn Feb 16, 2024, at 22:11, Cyclonecinta88 ***@***.***> wrote:﻿
Who the fuck you talking to captain cook ho I'll skull frag you ho

**Comment by Bbjj88h** [comment]
All talk over the ph ho I'll gutter stomp you then I'll piss in ur fn mouth
ho say it to my face ho I dare you piece of shit go get a fukn life

**Comment by CrytoCraze77** [comment]
😂😂it seems to me ur that 2&1/2 inches ur momma was moon about how good I felt and it was just like she was whatever it was just your sister😂😂😂hey yo 5524 Steele ridge road STL MO 63128 fuck u waiting on  so s so slickened by gotten away with other side screen like here how stop talking fucking mullah get your fucking bitch ass up here and shut the fuck upSent from my iPhoneOn Feb 17, 2024, at 04:36, Cyclonecinta88 ***@***.***> wrote:﻿
All talk over the ph ho I'll gutter stomp you then I'll piss in ur fn mouth

ho say it to my face ho I dare you piece of shit go get a fukn life

**Comment by Bbjj88h** [comment]
Funny funny funny 😂😂 hero stik ya chest in I'll cave it in get a fukn
life boood

**Comment by CrytoCraze77** [comment]
I have no life boood ever the fuck that mean or is I’ve chasing hopes and dreams down these shit hole rabbit holes u cunts create owe each day I awake more more more crippling pain not a single 1 FUCKING CLUE lol 😂😂😭😡fuck you i was on phone IRS 48 minutes yesterday that’s my salvation 46,000 between 2 chrome pages incognito other then that I’ve got nothing. And mean nothing since October 2022 Elon made surely certain of that all because I backed up Dr fauci yeah all know he is I got 12 or 24 time out 😂a real person time out from dick 1 on the planet well fuck the luck emails screen shot time THE TIME OMG stripped away from me fuck YOU BE IN REPORT TO MISGUIDED MAGGOT MOTHER FUCKER JEREMY CRIPPLING PAIN HIRYS SI MUCH Moyers fuck u lifeSent from my iPhoneOn Feb 17, 2024, at 05:24, Cyclonecinta88 ***@***.***> wrote:﻿
Funny funny funny 😂😂 hero stik ya chest in I'll cave it in get a fukn

life boood

**Comment by CrytoCraze77** [comment]
5524 Steele ridge. St. Louis Mo 63128U stupid cunt Sent from my iPhoneOn Feb 17, 2024, at 14:04, Jeremy M ***@***.***> wrote:﻿I have no life boood ever the fuck that mean or is I’ve chasing hopes and dreams down these shit hole rabbit holes u cunts create owe each day I awake more more more crippling pain not a single 1 FUCKING CLUE lol 😂😂😭😡fuck you i was on phone IRS 48 minutes yesterday that’s my salvation 46,000 between 2 chrome pages incognito other then that I’ve got nothing. And mean nothing since October 2022 Elon made surely certain of that all because I backed up Dr fauci yeah all know he is I got 12 or 24 time out 😂a real person time out from dick 1 on the planet well fuck the luck emails screen shot time THE TIME OMG stripped away from me fuck YOU BE IN REPORT TO MISGUIDED MAGGOT MOTHER FUCKER JEREMY CRIPPLING PAIN HIRYS SI MUCH Moyers fuck u lifeSent from my iPhoneOn Feb 17, 2024, at 05:24, Cyclonecinta88 ***@***.***> wrote:﻿
Funny funny funny 😂😂 hero stik ya chest in I'll cave it in get a fukn

life boood

**Comment by Robynofthewoods** [comment]
How. Do I get my money?

**Comment by CrytoCraze77** [comment]
﻿Wgy you so mean Rybon Elon calling lol you do everything he says let ask you wheh ladt time had pussy livked. Made out with huh??  Well this Ain’t over im vrimg on the best ur worst I fuvkin dare ya 🌹😘🇺🇸😂😘Sent from my iPhoneOn Feb 26, 2024, at 23:42, Robynofthewoods ***@***.***> wrote:﻿
How. Do I get my money?

**Comment by CrytoCraze77** [comment]
Why Stash WHY YOU FUCKIN DOING THS TO ME YOU GOT PROBLEM WITH MY ATITUDE GOT A PROBLEM MY REPONSES HOW FUCKIN LONG YOU THINK YOU COULD LASTED REALM OF POLITE BEFORE YOU FUCK N SNAP ANSWER ME DONT TYPES SAID FUCK YOU PIECE OF SHIT FUCK WHY,?! Why doing this me I never hurt you I never hurt anyine so why? I’m dirt poor nothing wake up more pain anyone other being would tapped out long ago so why WHY?Sent from my iPadOn Feb 26, 2024, at 23:42, Robynofthewoods ***@***.***> wrote:﻿
How. Do I get my money?

**Comment by CrytoCraze77** [comment]
Here let me add FUCK YOU CHICKEN SHIT FUCKIN BITCH CUNT RYBON OF THE WOOD WHATEVER UR A FUCKING ROBBER THATS FOR SURE SO LOL so what do I do ahh look n at these meds I don’t wanna take I hate you even more DOUBLE FUCK U CUNT CUNT 😎🇺🇸😘🖕🖕🖕Sent from my iPhoneOn Feb 27, 2024, at 03:15, Jeremy M ***@***.***> wrote:﻿﻿Wgy you so mean Rybon Elon calling lol you do everything he says let ask you wheh ladt time had pussy livked. Made out with huh??  Well this Ain’t over im vrimg on the best ur worst I fuvkin dare ya 🌹😘🇺🇸😂😘Sent from my iPhoneOn Feb 26, 2024, at 23:42, Robynofthewoods ***@***.***> wrote:﻿
How. Do I get my money?

**Comment by CrytoCraze77** [comment]
One last my daily bullshit instead losing my mind I’ve just shared it at all points possible share it with you community HAH fuvkin joke if not prove me otherwise I ain’t taking down nothing I don’t want to be on there I WANT WHATS MINE AND TO GIVE MY SON A HUG YOU GUYS HELP MAKE IT HAPPEN PLEASE MAKE IT HAPPEN UR ABLE TO do some really good please HELP ME STOP HURTIN ME PLEASE please Sent from my iPhoneOn Feb 27, 2024, at 03:15, Jeremy M ***@***.***> wrote:﻿﻿Wgy you so mean Rybon Elon calling lol you do everything he says let ask you wheh ladt time had pussy livked. Made out with huh??  Well this Ain’t over im vrimg on the best ur worst I fuvkin dare ya 🌹😘🇺🇸😂😘Sent from my iPhoneOn Feb 26, 2024, at 23:42, Robynofthewoods ***@***.***> wrote:﻿
How. Do I get my money?

**Comment by CrytoCraze77** [comment]
Something tells me demon won’t come here so what is this what’s next ??Sent from my iPhoneOn Feb 27, 2024, at 03:15, Jeremy M ***@***.***> wrote:﻿﻿Wgy you so mean Rybon Elon calling lol you do everything he says let ask you wheh ladt time had pussy livked. Made out with huh??  Well this Ain’t over im vrimg on the best ur worst I fuvkin dare ya 🌹😘🇺🇸😂😘Sent from my iPhoneOn Feb 26, 2024, at 23:42, Robynofthewoods ***@***.***> wrote:﻿
How. Do I get my money?

**Comment by CrytoCraze77** [comment]
Ooo you mother fuckers got balls that CLANCK So now what huh fuckin CLARITY say you chicken shits think all that safely behind a computer WTF DO YOU WANT IF YOU DONT SOMETHING ASAP I WILL GRT FIND SOMEONE TO BUST ALL U BITCHES U DONT LIKE MY WORDS U DUMB MOTHERLESS CUNTS ARE ONES UNLESSHED CALL ME IF YOU THINK UR BALLS REAKLY CLANK MAKE MR A HAPPILY NOT WORRYING ABOUT A GOD DAMN THING NOW!!!!!! 3149101139 like I gotta tell u I’m not playing you ain’t justice or right over wrong TRUTH SO TELL ME IMMEDIATELY UHH OWE WOO UR REALLY PISSIN ME OFF JEREMY Sent from my iPhoneOn Feb 27, 2024, at 03:15, Jeremy M ***@***.***> wrote:﻿﻿Wgy you so mean Rybon Elon calling lol you do everything he says let ask you wheh ladt time had pussy livked. Made out with huh??  Well this Ain’t over im vrimg on the best ur worst I fuvkin dare ya 🌹😘🇺🇸😂😘Sent from my iPhoneOn Feb 26, 2024, at 23:42, Robynofthewoods ***@***.***> wrote:﻿
How. Do I get my money?

**Comment by CrytoCraze77** [comment]
Oh rybon  I going local law going fbi building or hmm FUCK USent from my iPhoneOn Feb 27, 2024, at 03:15, Jeremy M ***@***.***> wrote:﻿﻿Wgy you so mean Rybon Elon calling lol you do everything he says let ask you wheh ladt time had pussy livked. Made out with huh??  Well this Ain’t over im vrimg on the best ur worst I fuvkin dare ya 🌹😘🇺🇸😂😘Sent from my iPhoneOn Feb 26, 2024, at 23:42, Robynofthewoods ***@***.***> wrote:﻿
How. Do I get my money?

**Comment by CrytoCraze77** [comment]
How do I get my money ?? Like playing mystery riddle wrapped up  n ass of enigma How do I get it ??Sent from my iPhoneOn Feb 27, 2024, at 03:15, Jeremy M ***@***.***> wrote:﻿﻿Wgy you so mean Rybon Elon calling lol you do everything he says let ask you wheh ladt time had pussy livked. Made out with huh??  Well this Ain’t over im vrimg on the best ur worst I fuvkin dare ya 🌹😘🇺🇸😂😘Sent from my iPhoneOn Feb 26, 2024, at 23:42, Robynofthewoods ***@***.***> wrote:﻿
How. Do I get my money?

**Comment by CrytoCraze77** [comment]
Well ?? You guys think you can just steal like that I will not EVER LET THIS FUKN GOSent from my iPhoneOn Feb 27, 2024, at 03:15, Jeremy M ***@***.***> wrote:﻿﻿Wgy you so mean Rybon Elon calling lol you do everything he says let ask you wheh ladt time had pussy livked. Made out with huh??  Well this Ain’t over im vrimg on the best ur worst I fuvkin dare ya 🌹😘🇺🇸😂😘Sent from my iPhoneOn Feb 26, 2024, at 23:42, Robynofthewoods ***@***.***> wrote:﻿
How. Do I get my money?

**Comment by CrytoCraze77** [comment]
FUCK YOU!!! Steal it from FBIJEREMY MOYERS Sent from my iPhoneOn Feb 27, 2024, at 03:15, Jeremy M ***@***.***> wrote:﻿﻿Wgy you so mean Rybon Elon calling lol you do everything he says let ask you wheh ladt time had pussy livked. Made out with huh??  Well this Ain’t over im vrimg on the best ur worst I fuvkin dare ya 🌹😘🇺🇸😂😘Sent from my iPhoneOn Feb 26, 2024, at 23:42, Robynofthewoods ***@***.***> wrote:﻿
How. Do I get my money?

**Comment by CrytoCraze77** [comment]
Hey you fuckin bitch pardon me on balls that clank fucked me got. A cunt that sharpest razor Ice sickles god dam those notes nothing to do years my mind and important down 11 iPad still had 91 oops left my service on you slippy fuck you bitch I’m three you all by a long YOU GOD DAMN FUCKIN READ ME 9 points entry this great state Missouri all day welcome to the SHOW ME STATE BITCH IM SHOW U IF LAST I DO FUCK N CUNT WHORE RYBON Sent from my iPhoneOn Feb 27, 2024, at 03:15, Jeremy M ***@***.***> wrote:﻿﻿Wgy you so mean Rybon Elon calling lol you do everything he says let ask you wheh ladt time had pussy livked. Made out with huh??  Well this Ain’t over im vrimg on the best ur worst I fuvkin dare ya 🌹😘🇺🇸😂😘Sent from my iPhoneOn Feb 26, 2024, at 23:42, Robynofthewoods ***@***.***> wrote:﻿
How. Do I get my money?

**Comment by CrytoCraze77** [comment]
How do get my data back who the fuck Is Stash to you lol you know well of coarse you know 200 different stocks more and so happens to be This one right and was it price sold it cause stash fucked me out $1000 pretty nice fuckin forgery’s did can’t tell oo one fine day we shall look into 1 another’s eyes I live for that day. Alone never been vengeful but I damn near mastered all. I’ve tried so well until that day hah 👍😉😎Sent from my iPhoneOn Feb 27, 2024, at 03:15, Jeremy M ***@***.***> wrote:﻿﻿Wgy you so mean Rybon Elon calling lol you do everything he says let ask you wheh ladt time had pussy livked. Made out with huh??  Well this Ain’t over im vrimg on the best ur worst I fuvkin dare ya 🌹😘🇺🇸😂😘Sent from my iPhoneOn Feb 26, 2024, at 23:42, Robynofthewoods ***@***.***> wrote:﻿
How. Do I get my money?
